FROM node:12-slim as builder

RUN apt update && apt install -y \
    libgtk2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2 \
    libxtst6 \
    xauth \
    xvfb && \
    rm -rf /var/lib/apt/lists/*

FROM builder as app

EXPOSE 8080
EXPOSE 4000

COPY yarn.lock package.json ./
RUN yarn install
COPY . .
